# Generated by Django 5.0.6 on 2024-06-23 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='message_to_admin',
            field=models.TextField(blank=True),
        ),
    ]
