# Generated by Django 5.0.6 on 2024-06-23 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_message_to_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactModelToAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_message', models.TextField(blank=True)),
            ],
        ),
    ]
